In [1]:
import pandas as pd
import statsmodels.api as sm

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/adiacla/bigdata/master/titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df = df.drop('Name', axis = 1)
df = df.drop('Cabin', axis = 1)
df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0              1         0       3    male  22.0      1      0   
1              2         1       1  female  38.0      1      0   
2              3         1       3  female  26.0      0      0   
3              4         1       1  female  35.0      1      0   
4              5         0       3    male  35.0      0      0   
..           ...       ...     ...     ...   ...    ...    ...   
886          887         0       2    male  27.0      0      0   
887          888         1       1  female  19.0      0      0   
888          889         0       3  female   NaN      1      2   
889          890         1       1    male  26.0      0      0   
890          891         0       3    male  32.0      0      0   

               Ticket     Fare Embarked  
0           A/5 21171   7.2500        S  
1            PC 17599  71.2833        C  
2    STON/O2. 3101282   7.9250        S  
3              113803  53.1000        S  
4              373450   8.0500        S  
..                ...      ...      ...  
886            211536  13.0000        S  
887            112053  30.0000        S  
888        W./C. 6607  23.4500        S  
889            111369  30.0000        C  
890            370376   7.7500        Q  

[891 rows x 10 columns]

In [5]:
df = df.dropna()
df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0              1         0       3    male  22.0      1      0   
1              2         1       1  female  38.0      1      0   
2              3         1       3  female  26.0      0      0   
3              4         1       1  female  35.0      1      0   
4              5         0       3    male  35.0      0      0   
..           ...       ...     ...     ...   ...    ...    ...   
885          886         0       3  female  39.0      0      5   
886          887         0       2    male  27.0      0      0   
887          888         1       1  female  19.0      0      0   
889          890         1       1    male  26.0      0      0   
890          891         0       3    male  32.0      0      0   

               Ticket     Fare Embarked  
0           A/5 21171   7.2500        S  
1            PC 17599  71.2833        C  
2    STON/O2. 3101282   7.9250        S  
3              113803  53.1000        S  
4              373450   8.0500        S  
..                ...      ...      ...  
885            382652  29.1250        Q  
886            211536  13.0000        S  
887            112053  30.0000        S  
889            111369  30.0000        C  
890            370376   7.7500        Q  

[712 rows x 10 columns]

In [6]:
df = df.drop('Ticket', axis = 1)
df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
885          886         0       3  female  39.0      0      5  29.1250   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
885        Q  
886        S  
887        S  
889        C  
890        Q  

[712 rows x 9 columns]

In [9]:
df["Sex2"] = 0
df.loc[df.Sex == "female", "Sex2"] = 0
df.loc[df.Sex == "male", "Sex2"] = 1
df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
885          886         0       3  female  39.0      0      5  29.1250   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  Sex2  
0          S     1  
1          C     0  
2          S     0  
3          S     0  
4          S     1  
..       ...   ...  
885        Q     0  
886        S     1  
887        S     0  
889        C     1  
890        Q     1  

[712 rows x 10 columns]

In [10]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked        object
Sex2             int64
dtype: object

In [12]:
df["EmbarkedC"] = 0
df.loc[df.Embarked == "C", "EmbarkedC"] = 1
df.loc[df.Embarked != "C", "EmbarkedC"] = 0
df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
885          886         0       3  female  39.0      0      5  29.1250   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  Sex2  EmbarkedC  
0          S     1          0  
1          C     0          1  
2          S     0          0  
3          S     0          0  
4          S     1          0  
..       ...   ...        ...  
885        Q     0          0  
886        S     1          0  
887        S     0          0  
889        C     1          1  
890        Q     1          0  

[712 rows x 11 columns]

In [14]:
df["EmbarkedQ"] = 0
df.loc[df.Embarked == "Q", "EmbarkedQ"] = 1
df.loc[df.Embarked != "Q", "EmbarkedQ"] = 0

df["EmbarkedS"] = 0
df.loc[df.Embarked == "S", "EmbarkedS"] = 1
df.loc[df.Embarked != "S", "EmbarkedS"] = 0

df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
885          886         0       3  female  39.0      0      5  29.1250   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  Sex2  EmbarkedC  EmbarkedQ  EmbarkedS  
0          S     1          0          0          1  
1          C     0          1          0          0  
2          S     0          0          0          1  
3          S     0          0          0          1  
4          S     1          0          0          1  
..       ...   ...        ...        ...        ...  
885        Q     0          0          1          0  
886        S     1          0          0          1  
887        S     0          0          0          1  
889        C     1          1          0          0  
890        Q     1          0          1          0  

[712 rows x 13 columns]

In [15]:
df = df.drop('Embarked', axis = 1)
df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  Sex2  \
0              1         0       3    male  22.0      1      0   7.2500     1   
1              2         1       1  female  38.0      1      0  71.2833     0   
2              3         1       3  female  26.0      0      0   7.9250     0   
3              4         1       1  female  35.0      1      0  53.1000     0   
4              5         0       3    male  35.0      0      0   8.0500     1   
..           ...       ...     ...     ...   ...    ...    ...      ...   ...   
885          886         0       3  female  39.0      0      5  29.1250     0   
886          887         0       2    male  27.0      0      0  13.0000     1   
887          888         1       1  female  19.0      0      0  30.0000     0   
889          890         1       1    male  26.0      0      0  30.0000     1   
890          891         0       3    male  32.0      0      0   7.7500     1   

     EmbarkedC  EmbarkedQ  EmbarkedS  
0            0          0          1  
1            1          0          0  
2            0          0          1  
3            0          0          1  
4            0          0          1  
..         ...        ...        ...  
885          0          1          0  
886          0          0          1  
887          0          0          1  
889          1          0          0  
890          0          1          0  

[712 rows x 12 columns]

In [16]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Sex2             int64
EmbarkedC        int64
EmbarkedQ        int64
EmbarkedS        int64
dtype: object

In [17]:
x =  df.iloc[:,[2,4,5,6,7,8,9,10,11]]
y =  df.Survived
logit_model=sm.Logit(y,x)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.444061
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:               Survived   No. Observations:                  712
Model:                          Logit   Df Residuals:                      703
Method:                           MLE   Df Model:                            8
Date:                Wed, 04 Oct 2023   Pseudo R-squ.:                  0.3419
Time:                        15:16:17   Log-Likelihood:                -316.17
converged:                       True   LL-Null:                       -480.45
Covariance Type:            nonrobust   LLR p-value:                 3.392e-66
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Pclass        -1.1993      0.165     -7.285      0.000      -1.522      -0.877
Age           -0.0433      0.

In [18]:
import numpy as np
from itertools import combinations

usefulColumns=[2,4,5,6,7,8,9,10,11]
combinaciones=[]

for i in range(1, len(usefulColumns)+1):
  temp = combinations(usefulColumns, i)
  for j in list(temp):
    combinaciones.append(np.array(j))
combinaciones

[array([2]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([2, 4]),
 array([2, 5]),
 array([2, 6]),
 array([2, 7]),
 array([2, 8]),
 array([2, 9]),
 array([ 2, 10]),
 array([ 2, 11]),
 array([4, 5]),
 array([4, 6]),
 array([4, 7]),
 array([4, 8]),
 array([4, 9]),
 array([ 4, 10]),
 array([ 4, 11]),
 array([5, 6]),
 array([5, 7]),
 array([5, 8]),
 array([5, 9]),
 array([ 5, 10]),
 array([ 5, 11]),
 array([6, 7]),
 array([6, 8]),
 array([6, 9]),
 array([ 6, 10]),
 array([ 6, 11]),
 array([7, 8]),
 array([7, 9]),
 array([ 7, 10]),
 array([ 7, 11]),
 array([8, 9]),
 array([ 8, 10]),
 array([ 8, 11]),
 array([ 9, 10]),
 array([ 9, 11]),
 array([10, 11]),
 array([2, 4, 5]),
 array([2, 4, 6]),
 array([2, 4, 7]),
 array([2, 4, 8]),
 array([2, 4, 9]),
 array([ 2,  4, 10]),
 array([ 2,  4, 11]),
 array([2, 5, 6]),
 array([2, 5, 7]),
 array([2, 5, 8]),
 array([2, 5, 9]),
 array([ 2,  5, 10]),
 array([ 2,  5, 11]),
 array([2, 6, 7]

In [20]:
#generar los pseudo r cuadrado
prsquared_values=[]

for i in range(len(combinaciones)):
  #Hacer regresion logistica
  x =  df.iloc[:, combinaciones[i]]
  y =  df.Survived
  print(combinaciones[i])
  logit_model=sm.Logit(y,x)
  result=logit_model.fit()
  prsquared_values.append(result.prsquared)

[2]
Optimization terminated successfully.
         Current function value: 0.646769
         Iterations 4
[4]
Optimization terminated successfully.
         Current function value: 0.671406
         Iterations 4
[5]
Optimization terminated successfully.
         Current function value: 0.687447
         Iterations 4
[6]
Optimization terminated successfully.
         Current function value: 0.693143
         Iterations 3
[7]
Optimization terminated successfully.
         Current function value: 0.686284
         Iterations 4
[8]
Optimization terminated successfully.
         Current function value: 0.575133
         Iterations 5
[9]
Optimization terminated successfully.
         Current function value: 0.688879
         Iterations 4
[10]
Optimization terminated successfully.
         Current function value: 0.689416
         Iterations 5
[11]
Optimization terminated successfully.
         Current function value: 0.663482
         Iterations 4
[2 4]
Optimization terminated successfully.


In [21]:
combinacionesDF = pd.DataFrame()
combinacionesDF['combinaciones'] = combinaciones
combinacionesDF['pseudo_r_squared'] = prsquared_values
combinacionesDF

combinaciones  pseudo_r_squared
0                              [2]          0.041529
1                              [4]          0.005018
2                              [5]         -0.018754
3                              [6]         -0.027195
4                              [7]         -0.017031
..                             ...               ...
506     [2, 4, 5, 7, 8, 9, 10, 11]          0.341680
507     [2, 4, 6, 7, 8, 9, 10, 11]          0.333016
508     [2, 5, 6, 7, 8, 9, 10, 11]          0.310285
509     [4, 5, 6, 7, 8, 9, 10, 11]          0.285418
510  [2, 4, 5, 6, 7, 8, 9, 10, 11]          0.341929

[511 rows x 2 columns]

In [22]:
#Ordenar las combinaciones de mejor a peor
bestCombinationsDF = combinacionesDF.sort_values(by='pseudo_r_squared', ascending=False)
bestCombinationsDF

combinaciones  pseudo_r_squared
510  [2, 4, 5, 6, 7, 8, 9, 10, 11]          0.341929
506     [2, 4, 5, 7, 8, 9, 10, 11]          0.341680
505     [2, 4, 5, 6, 8, 9, 10, 11]          0.341578
479        [2, 4, 5, 8, 9, 10, 11]          0.341437
507     [2, 4, 6, 7, 8, 9, 10, 11]          0.333016
..                             ...               ...
32                          [6, 9]         -0.020567
6                              [9]         -0.020876
33                         [6, 10]         -0.021660
7                             [10]         -0.021672
3                              [6]         -0.027195

[511 rows x 2 columns]

In [23]:
#Mostrar las 10 mejores combinaciones
bestCombinationsDF.head(10)

combinaciones  pseudo_r_squared
510  [2, 4, 5, 6, 7, 8, 9, 10, 11]          0.341929
506     [2, 4, 5, 7, 8, 9, 10, 11]          0.341680
505     [2, 4, 5, 6, 8, 9, 10, 11]          0.341578
479        [2, 4, 5, 8, 9, 10, 11]          0.341437
507     [2, 4, 6, 7, 8, 9, 10, 11]          0.333016
484        [2, 4, 6, 8, 9, 10, 11]          0.332957
485        [2, 4, 7, 8, 9, 10, 11]          0.331116
415           [2, 4, 8, 9, 10, 11]          0.331101
508     [2, 5, 6, 7, 8, 9, 10, 11]          0.310285
491        [2, 5, 7, 8, 9, 10, 11]          0.310064

In [24]:
#Definir cuantas se quieren mostrar
numComb=10
contador=0

for index, row in bestCombinationsDF.iterrows():
  #Mostrar numero de la combinacion
  contador=contador+1
  print("***Regresión logística número",contador,"***")
  print()
  print(row['combinaciones'])

  #Hacer regresion logistica
  x =  df.iloc[:, row['combinaciones']]
  y =  df.Survived
  logit_model=sm.Logit(y,x)
  result=logit_model.fit()
  print(result.summary())
  print()

  #gestionar cantidad de regresiones mostradas
  if contador == numComb:
        break

***Regresión logística número 1 ***

[ 2  4  5  6  7  8  9 10 11]
Optimization terminated successfully.
         Current function value: 0.444061
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:               Survived   No. Observations:                  712
Model:                          Logit   Df Residuals:                      703
Method:                           MLE   Df Model:                            8
Date:                Wed, 04 Oct 2023   Pseudo R-squ.:                  0.3419
Time:                        15:19:14   Log-Likelihood:                -316.17
converged:                       True   LL-Null:                       -480.45
Covariance Type:            nonrobust   LLR p-value:                 3.392e-66
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Pclass        -1.1993      0.165     -7.28

# **Taller 7**

In [25]:
combinaciones5 = [subarray for subarray in combinaciones if len(subarray) == 5]
combinaciones5

[array([2, 4, 5, 6, 7]),
 array([2, 4, 5, 6, 8]),
 array([2, 4, 5, 6, 9]),
 array([ 2,  4,  5,  6, 10]),
 array([ 2,  4,  5,  6, 11]),
 array([2, 4, 5, 7, 8]),
 array([2, 4, 5, 7, 9]),
 array([ 2,  4,  5,  7, 10]),
 array([ 2,  4,  5,  7, 11]),
 array([2, 4, 5, 8, 9]),
 array([ 2,  4,  5,  8, 10]),
 array([ 2,  4,  5,  8, 11]),
 array([ 2,  4,  5,  9, 10]),
 array([ 2,  4,  5,  9, 11]),
 array([ 2,  4,  5, 10, 11]),
 array([2, 4, 6, 7, 8]),
 array([2, 4, 6, 7, 9]),
 array([ 2,  4,  6,  7, 10]),
 array([ 2,  4,  6,  7, 11]),
 array([2, 4, 6, 8, 9]),
 array([ 2,  4,  6,  8, 10]),
 array([ 2,  4,  6,  8, 11]),
 array([ 2,  4,  6,  9, 10]),
 array([ 2,  4,  6,  9, 11]),
 array([ 2,  4,  6, 10, 11]),
 array([2, 4, 7, 8, 9]),
 array([ 2,  4,  7,  8, 10]),
 array([ 2,  4,  7,  8, 11]),
 array([ 2,  4,  7,  9, 10]),
 array([ 2,  4,  7,  9, 11]),
 array([ 2,  4,  7, 10, 11]),
 array([ 2,  4,  8,  9, 10]),
 array([ 2,  4,  8,  9, 11]),
 array([ 2,  4,  8, 10, 11]),
 array([ 2,  4,  9, 10, 11]),


In [26]:
#Verificar cantidad de comnbinaciones
len(combinaciones5)

126

In [27]:
#Obtener los pseudo r-cuadrado
prsquared_values=[]

for i in range(len(combinaciones5)):
  #Hacer regresion logistica
  x =  df.iloc[:, combinaciones5[i]]
  y =  df.Survived
  print(combinaciones5[i])
  logit_model=sm.Logit(y,x)
  result=logit_model.fit()
  prsquared_values.append(result.prsquared)

[2 4 5 6 7]
Optimization terminated successfully.
         Current function value: 0.604452
         Iterations 6
[2 4 5 6 8]
Optimization terminated successfully.
         Current function value: 0.547571
         Iterations 5
[2 4 5 6 9]
Optimization terminated successfully.
         Current function value: 0.617091
         Iterations 5
[ 2  4  5  6 10]
Optimization terminated successfully.
         Current function value: 0.634581
         Iterations 5
[ 2  4  5  6 11]
Optimization terminated successfully.
         Current function value: 0.634637
         Iterations 5
[2 4 5 7 8]
Optimization terminated successfully.
         Current function value: 0.510103
         Iterations 6
[2 4 5 7 9]
Optimization terminated successfully.
         Current function value: 0.600594
         Iterations 6
[ 2  4  5  7 10]
Optimization terminated successfully.
         Current function value: 0.606738
         Iterations 6
[ 2  4  5  7 11]
Optimization terminated successfully.
         Current f

In [28]:
combinacionesDF5 = pd.DataFrame()
combinacionesDF5['combinaciones'] = combinaciones5
combinacionesDF5['pseudo_r_squared'] = prsquared_values
combinacionesDF5

combinaciones  pseudo_r_squared
0      [2, 4, 5, 6, 7]          0.104239
1      [2, 4, 5, 6, 8]          0.188533
2      [2, 4, 5, 6, 9]          0.085510
3     [2, 4, 5, 6, 10]          0.059590
4     [2, 4, 5, 6, 11]          0.059507
..                 ...               ...
121   [6, 7, 8, 9, 11]          0.269287
122  [6, 7, 8, 10, 11]          0.242397
123  [6, 7, 9, 10, 11]          0.075240
124  [6, 8, 9, 10, 11]          0.244192
125  [7, 8, 9, 10, 11]          0.263639

[126 rows x 2 columns]

In [29]:
#Ordenar las combinaciones de mejor a peor
bestCombinationsDF5 = combinacionesDF5.sort_values(by='pseudo_r_squared', ascending=False)
bestCombinationsDF5

combinaciones  pseudo_r_squared
69   [2, 8, 9, 10, 11]          0.306294
32    [2, 4, 8, 9, 11]          0.294771
66    [2, 7, 8, 9, 11]          0.290562
52    [2, 5, 8, 9, 11]          0.289736
62    [2, 6, 8, 9, 11]          0.287535
..                 ...               ...
99   [4, 6, 9, 10, 11]          0.039972
114  [5, 6, 9, 10, 11]          0.037260
89   [4, 5, 9, 10, 11]          0.035933
79   [4, 5, 6, 10, 11]          0.033016
108   [5, 6, 7, 9, 10]          0.009770

[126 rows x 2 columns]

In [30]:
#Obtener mejor combinacion
mejor5=bestCombinationsDF5.iloc[0]['combinaciones']
mejor5

array([ 2,  8,  9, 10, 11])

In [31]:
#Hacer regresion logistica con mejor combinacion de 5
x =  df.iloc[:, mejor5]
y =  df.Survived
logit_model=sm.Logit(y,x)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.468107
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:               Survived   No. Observations:                  712
Model:                          Logit   Df Residuals:                      707
Method:                           MLE   Df Model:                            4
Date:                Wed, 04 Oct 2023   Pseudo R-squ.:                  0.3063
Time:                        15:32:15   Log-Likelihood:                -333.29
converged:                       True   LL-Null:                       -480.45
Covariance Type:            nonrobust   LLR p-value:                 1.820e-62
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Pclass        -0.9161      0.122     -7.504      0.000      -1.155      -0.677
Sex2          -2.5726      0.

In [32]:
from sklearn.model_selection import train_test_split

#Definir columnas a usar
x =  df.iloc[:, mejor5]
y =  df.Survived

# Separar train y test
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Guardar train y test como constante
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

#Entrenar modelo con train
logit_model = sm.Logit(y_train, X_train)
result = logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.450007
         Iterations 10
                           Logit Regression Results                           
Dep. Variable:               Survived   No. Observations:                  569
Model:                          Logit   Df Residuals:                      564
Method:                           MLE   Df Model:                            4
Date:                Wed, 04 Oct 2023   Pseudo R-squ.:                  0.3295
Time:                        15:32:30   Log-Likelihood:                -256.05
converged:                       True   LL-Null:                       -381.86
Covariance Type:            nonrobust   LLR p-value:                 2.912e-53
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.6346        nan        nan        nan         nan         nan
Pclass        -1.0570      0

In [33]:
# Hacer predicciones con test y etiquetar como 1 o 0
y_prob = result.predict(X_test)
y_pred = (y_prob > 0.5).astype(int)

In [34]:
#Generar matriz de confusion

from sklearn.metrics import confusion_matrix

confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[66 14]
 [20 43]]


In [35]:
#obtener verdadero positivo, falso positivo, verdadero negativo y falso negativo
tn = confusion_matrix[0, 0]
fp = confusion_matrix[0, 1]
fn = confusion_matrix[1,0]
tp = confusion_matrix[1, 1]

print("Verdaderos negativos:",tn)
print("falsos positivos:",fp)
print("falsos negativos:",fn)
print("verdaderos positivos:",tp)

Verdaderos negativos: 66
falsos positivos: 14
falsos negativos: 20
verdaderos positivos: 43


In [36]:
#Obtener precision y exhaustividad

precision=tp/(tp+fp)
exhaustividad=tp/(tp+fn)

print("Precisión:",precision)
print("Exhaustividad:",exhaustividad)

Precisión: 0.7543859649122807
Exhaustividad: 0.6825396825396826
